fra.txt formatted

diff --git a/matplotlib-3.3.3/build/freetype-2.6.1/builds/unix/install-sh b/matplotlib-3.3.3/build/freetype-2.6.1/builds/unix/install-sh
--- a/matplotlib-3.3.3/build/freetype-2.6.1/builds/unix/install-sh
+++ b/matplotlib-3.3.3/build/freetype-2.6.1/builds/unix/install-sh
@@ -98,15 +98,15 @@ Options:
      --help     display this help and exit.
      --version  display version info and exit.
 
-  -c            (ignored)
-  -C            install only if different (preserve the last data modification time)
-  -d            create directories instead of installing files.
+    (ignored)
+    install only if different (preserve the last data modification time)
+    create directories instead of installing files.
   -g GROUP      $chgrpprog installed files to GROUP.
   -m MODE       $chmodprog installed files to MODE.
   -o USER       $chownprog installed files to USER.
-  -s            $stripprog installed files.
+    $stripprog installed files.
   -t DIRECTORY  install into DIRECTORY.
-  -T            report an error if DSTFILE is a directory.
+    report an error if DSTFILE is a directory.
 
 Environment variables override the default commands:
   CHGRPPROG CHMODPROG CHOWNPROG CMPPROG CPPROG MKDIRPROG MVPROG
@@ -127,12 +127,8 @@ while test $# -ne 0; do
     --help) echo "$usage"; exit $?;;
 
     -m) mode=$2
-        case $mode in
-          *' '* | *"$tab"* | *"$nl"* | *'*'* | *'?'* | *'['*)
-            echo "$0: invalid mode: $mode" >&2
-            exit 1;;
-        esac
-        shift;;
+        case $mode in*' '* | *"$tab"* | *"$nl"* | *'*'* | *'?'* | *'['*)  echo "$0: invalid mode: $mode" >&2  exit 1;;
+      shift;;
 
     -o) chowncmd="$chownprog $2"
         shift;;
@@ -141,12 +137,9 @@ while test $# -ne 0; do
 
     -t)
         is_target_a_directory=always
-        dst_arg=$2
-        # Protect names problematic for 'test' and other utilities.
-        case $dst_arg in
-          -* | [=\(\)!]) dst_arg=./$dst_arg;;
-        esac
-        shift;;
+        dst_arg=$2Protect names problematic for 'test' and other utilities.
+        case $dst_arg in-* | [=\(\)!]) dst_arg=./$dst_arg;;
+      shift;;
 
     -T) is_target_a_directory=never;;
 
@@ -179,8 +172,7 @@ if test $# -ne 0 && test -z "$dir_arg$dst_arg"; then
   # Otherwise, the last argument is the destination.  Remove it from $@.
   for arg
   do
-    if test -n "$dst_arg"; then
-      # $@ is not empty: it contains at least $arg.
+    if test -n "$dst_arg"; then is not empty: it contains at least $arg.
       set fnord "$@" "$dst_arg"
       shift # fnord
     fi
@@ -229,15 +221,13 @@ if test -z "$dir_arg"; then
     *[0-7])
       if test -z "$stripcmd"; then
         u_plus_rw=
-      else
-        u_plus_rw='% 200'
+    u_plus_rw='% 200'
       fi
       cp_umask=`expr '(' 777 - $mode % 1000 ')' $u_plus_rw`;;
     *)
       if test -z "$stripcmd"; then
         u_plus_rw=
-      else
-        u_plus_rw=,u+rw
+    u_plus_rw=,u+rw
       fi
       cp_umask=$mode$u_plus_rw;;
   esac
@@ -277,12 +267,10 @@ do
       if test "$is_target_a_directory" = never; then
         echo "$0: $dst_arg: Is a directory" >&2
         exit 1
-      fi
-      dstdir=$dst
+   $dst
       dst=$dstdir/`basename "$src"`
       dstdir_status=0
-    else
-      dstdir=`dirname "$dst"`
+ `dirname "$dst"`
       test -d "$dstdir"
       dstdir_status=$?
     fi
@@ -292,74 +280,23 @@ do
 
   if test $dstdir_status != 0; then
     case $posix_mkdir in
-      '')
-        # Create intermediate dirs using mode 755 as modified by the umask.
-        # This is like FreeBSD 'install' as of 1997-10-28.
+      '')Create intermediate dirs using mode 755 as modified by the umask.This is like FreeBSD 'install' as of 1997-10-28.
         umask=`umask`
-        case $stripcmd.$umask in
-          # Optimize common cases.
-          *[2367][2367]) mkdir_umask=$umask;;
-          .*0[02][02] | .[02][02] | .[02]) mkdir_umask=22;;
-
-          *[0-7])
-            mkdir_umask=`expr $umask + 22 \
-              - $umask % 100 % 40 + $umask % 20 \
-              - $umask % 10 % 4 + $umask % 2
-            `;;
-          *) mkdir_umask=$umask,go-w;;
+        case $stripcmd.$umask in# Optimize common cases.*[2367][2367]) mkdir_umask=$umask;;.*0[02][02] | .[02][02] | .[02]) mkdir_umask=22;;
+*[0-7])  mkdir_umask=`expr $umask +% 100 % 40 + $umask %% 10 % 4 + $umask % 2  `;;*) mkdir_umask=$umask,go-w;;
         esac
-
-        # With -d, create the new directory with the user-specified mode.
-        # Otherwise, rely on $mkdir_umask.
-        if test -n "$dir_arg"; then
-          mkdir_mode=-m$mode
-        else
-          mkdir_mode=
+With -d, create the new directory with the user-specified mode.Otherwise, rely on $mkdir_umask.
+        if test -n "$dir_arg"; thenmkdir_mode=-m$mode
+        mkdir_mode=
         fi
 
         posix_mkdir=false
-        case $umask in
-          *[123567][0-7][0-7])
-            # POSIX mkdir -p sets u+wx bits regardless of umask, which
-            # is incompatible with FreeBSD 'install' when (umask & 300) != 0.
-            ;;
-          *)
-            tmpdir=${TMPDIR-/tmp}/ins$RANDOM-$$
-            trap 'ret=$?; rmdir "$tmpdir/d" "$tmpdir" 2>/dev/null; exit $ret' 0
-
-            if (umask $mkdir_umask &&
-                exec $mkdirprog $mkdir_mode -p -- "$tmpdir/d") >/dev/null 2>&1
-            then
-              if test -z "$dir_arg" || {
-                   # Check for POSIX incompatibilities with -m.
-                   # HP-UX 11.23 and IRIX 6.5 mkdir -m -p sets group- or
-                   # other-writable bit of parent directory when it shouldn't.
-                   # FreeBSD 6.1 mkdir -m -p sets mode of existing directory.
-                   ls_ld_tmpdir=`ls -ld "$tmpdir"`
-                   case $ls_ld_tmpdir in
-                     d????-?r-*) different_mode=700;;
-                     d????-?--*) different_mode=755;;
-                     *) false;;
-                   esac &&
-                   $mkdirprog -m$different_mode -p -- "$tmpdir" && {
-                     ls_ld_tmpdir_1=`ls -ld "$tmpdir"`
-                     test "$ls_ld_tmpdir" = "$ls_ld_tmpdir_1"
-                   }
-                 }
-              then posix_mkdir=:
-              fi
-              rmdir "$tmpdir/d" "$tmpdir"
-            else
-              # Remove any dirs left behind by ancient mkdir implementations.
-              rmdir ./$mkdir_mode ./-p ./-- 2>/dev/null
-            fi
-            trap '' 0;;
+        case $umask in*[123567][0-7][0-7])  # POSIX mkdir -p sets u+wx bits regardless of umask, which  # is incompatible with FreeBSD 'install' when (umask & 300) != 0.  ;;*)  tmpdir=${TMPDIR-/tmp}/ins$RANDOM-$$  trap 'ret=$?; rmdir "$tmpdir/d" "$tmpdir" 2>/dev/null; exit $ret' 0
+  if (umask $mkdir_umask &&      exec $mkdirprog $mkdir_mode -p -- "$tmpdir/d") >/dev/null 2>&1  then    if test -z "$dir_arg" | # Check for POSIX incompatibilities with -m.HP-UX 11.23 and IRIX 6.5 mkdir -m -p sets group- orother-writable bit of parent directory when it shouldn't.FreeBSD 6.1 mkdir -m -p sets mode of existing directory.         ls_ld_tmpdir=`ls -ld "$tmpdir"`         case $ls_ld_tmpdir ind????-?r-*) different_mode=700;;d????-?--*) different_mode=755;;*) false;;         esac &&-m$different_mode -p -- "$tmpdir" &   ls_ld_tmpdir_1=`ls -ld "$tmpdir"`test "$ls_ld_tmpdir" = "$ls_ld_tmpdir_1"           then posix_mkdir=:        rmdir "$tmpdir/d" "$tmpdir"  else    # Remove any dirs left behind by ancient mkdir implementations.    rmdir ./$mkdir_mode ./-p ./-- 2>/dev/null  fi  trap '' 0;;
         esac;;
     esac
 
-    if
-      $posix_mkdir && (
-        umask $mkdir_umask &&
+ posix_mkdir & umask $mkdir_umask &&
         $doit_exec $mkdirprog $mkdir_mode -p -- "$dstdir"
       )
     then :
@@ -369,51 +306,28 @@ do
       # or it failed possibly due to a race condition.  Create the
       # directory the slow way, step by step, checking for races as we go.
 
-      case $dstdir in
-        /*) prefix='/';;
-        [-=\(\)!]*) prefix='./';;
-        *)  prefix='';;
+      case $dstdir in) prefix='/';;=\(\)!]*) prefix='./';;  prefix='';;
       esac
 
       oIFS=$IFS
       IFS=/
       set -f
       set fnord $dstdir
-      shift
-      set +f
+   +f
       IFS=$oIFS
 
       prefixes=
 
       for d
-      do
-        test X"$d" = X && continue
+    test X"$d" = X && continue
 
         prefix=$prefix$d
-        if test -d "$prefix"; then
-          prefixes=
-        else
-          if $posix_mkdir; then
-            (umask=$mkdir_umask &&
-             $doit_exec $mkdirprog $mkdir_mode -p -- "$dstdir") && break
-            # Don't fail if two instances are running concurrently.
-            test -d "$prefix" || exit 1
-          else
-            case $prefix in
-              *\'*) qprefix=`echo "$prefix" | sed "s/'/'\\\\\\\\''/g"`;;
-              *) qprefix=$prefix;;
-            esac
-            prefixes="$prefixes '$qprefix'"
-          fi
-        fi
-        prefix=$prefix/
+        if test -d "$prefix"; thenprefixes=
+        if $posix_mkdir; then  (umask=$mkdir_umask &&   $doit_exec $mkdirprog $mkdir_mode -p -- "$dstdir") && break  # Don't fail if two instances are running concurrently.  test -d "$prefix" || exit 1else  case $prefix in    *\'*) qprefix=`echo "$prefix" | sed "s/'/'\\\\\\\\''/g"`;;    *) qprefix=$prefix;;  esac  prefixes="$prefixes '$qprefix'"fi
+      prefix=$prefix/
       done
 
-      if test -n "$prefixes"; then
-        # Don't fail if two instances are running concurrently.
-        (umask $mkdir_umask &&
-         eval "\$doit_exec \$mkdirprog $prefixes") ||
-          test -d "$dstdir" || exit 1
+      if test -n "$prefixes"; thenDon't fail if two instances are running concurrently.$mkdir_umask &&"\$doit_exec \$mkdirprog $prefixes") ||test -d "$dstdir" || exit 1
         obsolete_mkdir_used=true
       fi
     fi
@@ -457,34 +371,15 @@ do
        set +f &&
        test "$old" = "$new" &&
        $cmpprog "$dst" "$dsttmp" >/dev/null 2>&1
-    then
-      rm -f "$dsttmp"
-    else
-      # Rename the file to the real destination.
+ -f "$dsttmp"
+  Rename the file to the real destination.
       $doit $mvcmd -f "$dsttmp" "$dst" 2>/dev/null ||
 
       # The rename failed, perhaps because mv can't rename something else
       # to itself, or perhaps because mv is so ancient that it does not
       # support -f.
-      {
-        # Now remove or move aside any old file at destination location.
-        # We try this two ways since rm can't unlink itself on some
-        # systems and the destination file might be busy for other
-        # reasons.  In this case, the final cleanup might fail but the new
-        # file should still install successfully.
-        {
-          test ! -f "$dst" ||
-          $doit $rmcmd -f "$dst" 2>/dev/null ||
-          { $doit $mvcmd -f "$dst" "$rmtmp" 2>/dev/null &&
-            { $doit $rmcmd -f "$rmtmp" 2>/dev/null; :; }
-          } ||
-          { echo "$0: cannot unlink or rename $dst" >&2
-            (exit 1); exit 1
-          }
-        } &&
-
-        # Now rename the file to the real destination.
-        $doit $mvcmd "$dsttmp" "$dst"
+     # Now remove or move aside any old file at destination location.We try this two ways since rm can't unlink itself on somesystems and the destination file might be busy for otherreasons.  In this case, the final cleanup might fail but the newfile should still install successfully.! -f "$dst" ||$doit $rmcmd -f "$dst" 2>/dev/null ||{ $doit $mvcmd -f "$dst" "$rmtmp" 2>/dev/null &&  { $doit $rmcmd -f "$rmtmp" 2>/dev/null; :   } ||{ echo "$0: cannot unlink or rename $dst" >&2  (exit 1); exit 1}&&
+Now rename the file to the real destination.$mvcmd "$dsttmp" "$dst"
       }
     fi || exit 1
 
